### ISSUE TITLE
[BUG] Uno.WinUI RxApp.MainThreadScheduler.Schedule not on main thread

### ISSUE THREAD

**Issue by msneijders** [reactiveui/ReactiveUI.Uno#22]
**Describe the bug**
Using ReactiveUI.Uno.WinUI, my ViewModel throws RuntimeExceptions like 'The application called an interface that was marshalled for a different thread', despite using `ObserveOn(RxApp.MainThreadScheduler)`.

Also code like `RxApp.MainThreadScheduler.Schedule(() => IsBusy = false)`, the delegate is not executed on the main thread.

**Steps To Reproduce**

Small solution based on latest visual studio Uno template, Windows only.

[UnoWinUI_ReactiveUI_MainThreadScheduler.zip](https://github.com/reactiveui/ReactiveUI.Uno/files/9639422/UnoWinUI_ReactiveUI_MainThreadScheduler.zip)

Provide the steps to reproduce the behaviour:

1. type something in the search textbox.
2. A TextBlock bounded to `ViewModel.SearchResult` ends in the error.
​

**Expected behaviour**
I am expecting the viewmodel property `SearchResult` to be set on the main thread, so it does not throw the 'marshalled for a different thread' exception.

**Environment**
- Windows: 11 Pro 22000.1042
- ReactiveUI Version:    18.3.1
- ReactiveUI.Uno.WinUI Version: 18.1.20

**Comment by msneijders** [comment]
P.S. In a WinUI project (no Uno, but "native"), a copy of this code works as expected, using nuget package "ReactiveUI.WinUI" -- tried using this package in the Uno.WinUI project, but gives the same runtime exceptions.

**Comment by glennawatson** [comment]
It's likely we aren't setting the scheduler properly so it's defaulting to the regular one, or we aren't checking for the uno winui package in the main rxui registration system

**Comment by msneijders** [comment]
I got my Uno.Windows project working, using package "ReactiveUI.WinUI" -- a difference I see is in the `Registrations.cs`:

- **ReactiveUI.WinUI** uses `RxApp.MainThreadScheduler = new WaitForDispatcherScheduler(() => DispatcherQueueScheduler.Current);`
- **ReactiveUI.Uno.WinUI** uses `RxApp.MainThreadScheduler = new WaitForDispatcherScheduler(() => CoreDispatcherScheduler.Current);`

Should I just use ReactiveUI.WinUI? I am a bit confused.

**Comment by glennawatson** [comment]
I think it's a bug. I will push a fix tomorrow. 

Thanks for doing the investigation
